name: Tag a new seat-docker release
on:
  release:
    types: [released]

jobs:
  build:
    name: Checkout and tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: eveseat/seat-docker
          ssh-key: '${{ secrets.SEAT_DOCKER_REPO }}'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          currver=`cat version`
          a=(${currver//./ })
          ((a[2]++))
          newver="${a[0]}.${a[1]}.${a[2]}"
          echo $newver > version
          git add version
          git commit -m "bump to version $newver"
          git push
          git tag -a "$newver" -m "src: $GITHUB_REPOSITORY commit: ${GITHUB_SHA: -8}"
          git push origin --tags

